import { useState, useEffect } from 'react'
import { getCertificate } from '../api'

export default function FairnessCertificate({ datasetId }) {
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    setLoading(true)
    getCertificate(datasetId)
      .then(setData)
      .catch(() => setData(null))
      .finally(() => setLoading(false))
  }, [datasetId])

  if (loading) return (
    <div className="loader"><div className="spinner" /><span className="loading-text">&gt; generating fairness certificate...</span></div>
  )
  if (!data) return <div className="empty-state"><div className="empty-state-title">Certificate generation failed</div></div>

  const statusColor = data.status === 'CERTIFIED' ? 'var(--green)' : data.status === 'CONDITIONAL' ? 'var(--amber)' : 'var(--red)'
  const statusBg = data.status === 'CERTIFIED' ? 'var(--green-dim)' : data.status === 'CONDITIONAL' ? 'var(--amber-dim)' : 'var(--red-dim)'

  const downloadCert = () => {
    const text = `
═══════════════════════════════════════════════
       FAIRLENS FAIRNESS CERTIFICATE
═══════════════════════════════════════════════

Certificate ID: ${data.certificate_id}
Status: ${data.status}
Issued: ${data.issued_date}

Overall Fairness Score: ${(data.overall_score * 100).toFixed(0)}%

Compliance Checks Passed: ${data.compliance_checks_passed}
Compliance Violations: ${data.compliance_violations}

Per-Attribute Results:
${Object.entries(data.per_attribute || {}).map(([attr, m]) =>
  `  ${attr}: ${(m.fairness_score * 100).toFixed(0)}% fairness | DI: ${m.disparate_impact} | ${m.status}`
).join('\n')}

Recommendations:
${data.recommendations?.map(r => `  • ${r}`).join('\n')}

Verification URL: ${data.qr_url}

═══════════════════════════════════════════════
This certificate was generated by FairLens
AI Bias Detection Platform
═══════════════════════════════════════════════
`
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `fairness-certificate-${data.certificate_id}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="animate-fade-in stagger-children">
      <div className="section-header" style={{ marginBottom: '2rem' }}>
        <div>
          <div className="section-eyebrow">GOVERNANCE / CERTIFICATE</div>
          <h1 className="section-title">Fairness Certificate</h1>
        </div>
        <button className="btn btn-primary" onClick={downloadCert}>↓ Download Certificate</button>
      </div>

      {/* Certificate Card */}
      <div className="card" style={{ border: `2px solid ${statusColor}`, maxWidth: 600, margin: '0 auto' }}>
        <div style={{ padding: '3rem 2.5rem', textAlign: 'center' }}>
          {/* Top badge */}
          <div style={{
            fontFamily: 'var(--font-mono)', fontSize: '0.55rem', textTransform: 'uppercase',
            letterSpacing: '0.2em', color: statusColor, marginBottom: '1.5rem',
          }}>
            ─── FAIRLENS ───
          </div>

          {/* Status */}
          <div style={{
            display: 'inline-block', padding: '8px 24px',
            background: statusBg, border: `1px solid ${statusColor}`,
            fontFamily: 'var(--font-serif)', fontSize: '1.8rem', fontWeight: 900,
            color: statusColor, letterSpacing: '0.1em', marginBottom: '1.5rem',
          }}>
            {data.status}
          </div>

          {/* Score */}
          <div style={{ marginBottom: '1.5rem' }}>
            <div style={{ fontFamily: 'var(--font-serif)', fontSize: '3rem', fontWeight: 900, color: 'var(--text-1)', lineHeight: 1 }}>
              {(data.overall_score * 100).toFixed(0)}%
            </div>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.6rem', color: 'var(--text-4)', marginTop: '0.25rem' }}>
              FAIRNESS SCORE
            </div>
          </div>

          {/* Details */}
          <div style={{
            borderTop: '1px solid var(--border)', borderBottom: '1px solid var(--border)',
            padding: '1rem 0', marginBottom: '1.5rem',
            fontFamily: 'var(--font-mono)', fontSize: '0.68rem', color: 'var(--text-3)',
          }}>
            <div>{data.compliance_checks_passed} compliance checks passed · {data.compliance_violations} violations</div>
            <div style={{ marginTop: '0.25rem' }}>{data.dataset_rows} records analyzed</div>
          </div>

          {/* Per-attribute breakdown */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem', marginBottom: '1.5rem' }}>
            {Object.entries(data.per_attribute || {}).map(([attr, m]) => (
              <div key={attr} style={{
                display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                padding: '0.5rem 0.75rem', background: 'var(--surface-2)',
                fontFamily: 'var(--font-mono)', fontSize: '0.68rem',
              }}>
                <span style={{ color: 'var(--text-2)', textTransform: 'capitalize' }}>{attr}</span>
                <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
                  <span style={{ color: 'var(--text-3)' }}>DI: {m.disparate_impact}</span>
                  <span style={{
                    padding: '2px 8px', fontSize: '0.55rem', fontWeight: 700,
                    background: m.status === 'PASS' ? 'var(--green-dim)' : 'var(--red-dim)',
                    color: m.status === 'PASS' ? 'var(--green)' : 'var(--red)',
                  }}>
                    {m.status}
                  </span>
                </div>
              </div>
            ))}
          </div>

          {/* Certificate ID */}
          <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.55rem', color: 'var(--text-4)' }}>
            <div>Certificate ID: {data.certificate_id}</div>
            <div>Issued: {data.issued_date}</div>
            <div style={{ marginTop: '0.5rem', color: 'var(--lime)' }}>
              {data.qr_url}
            </div>
          </div>
        </div>
      </div>

      {/* Recommendations */}
      <div className="card" style={{ marginTop: '1.5rem' }}>
        <div className="card-header"><span>Recommendations</span></div>
        <div style={{ padding: '1rem 1.25rem' }}>
          {data.recommendations?.map((r, i) => (
            <div key={i} style={{
              display: 'flex', gap: '10px', padding: '0.5rem 0',
              fontFamily: 'var(--font-mono)', fontSize: '0.72rem', color: 'var(--text-2)',
            }}>
              <span style={{ color: 'var(--lime)' }}>›</span>
              {r}
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
