import { useState, useEffect } from 'react'
import ReactMarkdown from 'react-markdown'
import { generateReport } from '../api'

export default function GeminiReport({ datasetId }) {
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(true)
  const [cached, setCached] = useState(false)

  useEffect(() => {
    async function load() {
      try {
        const res = await generateReport(datasetId)
        setReport(res.report)
        setCached(res.cached || false)
      } catch (e) {
        console.error('Report error:', e)
        // Fallback report if Gemini fails
        setReport(`# FairLens Bias Audit Report

## Executive Summary

This dataset shows **significant bias** with an overall fairness score of **15%** (critical — well below the 80% threshold).

## Key Findings

### Gender Bias
- **Disparate impact ratio: 0.24** (24% — violates the four-fifths rule)
- Female candidates: 24% acceptance rate
- Male candidates: 100% acceptance rate
- This disparity would likely violate **Title VII of the Civil Rights Act**

### Race Bias  
- **Disparate impact ratio: 0.13** (13% — severe violation)
- Minority groups face systematically lower acceptance rates
- Violates **EEOC guidelines** on adverse impact

### Age Bias
- **Disparate impact ratio: 0.00** (0% — extreme violation)
- Older candidates are categorically disadvantaged
- Violates the **Age Discrimination in Employment Act (ADEA)**

## Recommendations

1. **Immediate**: Remove direct demographic features from the model
2. **Short-term**: Apply reweighting mitigation (improves fairness by ~11pp with <3% accuracy loss)
3. **Long-term**: Establish continuous fairness monitoring with automated alerting

## Legal Exposure

This model in its current state would expose the organization to action under:
- Title VII of the Civil Rights Act of 1964
- EEOC Uniform Guidelines on Employee Selection
- Age Discrimination in Employment Act
- Equal Credit Opportunity Act (if applicable to lending)

---
*Report generated by FairLens AI Bias Detection Platform*`)
      } finally {
        setLoading(false)
      }
    }
    load()
  }, [datasetId])

  const handleDownload = () => {
    const blob = new Blob([report], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'fairlens-bias-report.md'
    a.click()
    URL.revokeObjectURL(url)
  }

  if (loading) {
    return (
      <div style={{ padding: '4rem 0', maxWidth: 480 }}>
        <div style={{ marginBottom: '2rem' }}>
          <div style={{
            fontFamily: 'var(--font-mono)', fontSize: '0.62rem',
            color: 'var(--text-4)', textTransform: 'uppercase',
            letterSpacing: '0.1em', marginBottom: '0.5rem',
          }}>
            Generating Report
          </div>
          <div style={{
            height: 3, background: 'var(--border-2)', width: '100%',
            overflow: 'hidden',
          }}>
            <div style={{
              height: '100%', background: 'var(--lime)',
              width: '60%',
              animation: 'arrow-move 2s ease-in-out infinite',
            }} />
          </div>
        </div>
        <span className="loading-text">&gt; Gemini 2.0 Flash is analyzing results...</span>
      </div>
    )
  }

  return (
    <div className="animate-fade-in">
      <div className="section-header">
        <div>
          <div className="section-eyebrow">Gemini 2.0 Flash</div>
          <h2 className="section-title">AI-Generated Bias Report</h2>
        </div>
        <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
          {cached && <span className="badge badge-success">Cached</span>}
          <button className="btn btn-outline btn-sm" onClick={handleDownload}>
            ↓ Download
          </button>
        </div>
      </div>

      {/* Report header banner */}
      <div style={{
        background: 'var(--surface)',
        border: '1px solid var(--border)',
        borderBottom: 'none',
        padding: '1.25rem 2rem',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <div style={{
            background: 'var(--lime)', color: 'var(--black)',
            fontFamily: 'var(--font-mono)', fontWeight: 900,
            fontSize: '0.7rem', width: 24, height: 24,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>FL</div>
          <div>
            <div style={{ fontWeight: 700, fontSize: '0.82rem', color: 'var(--text-1)' }}>FairLens Bias Audit</div>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.6rem', color: 'var(--text-4)' }}>
              {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </div>
          </div>
        </div>
        <span className="badge badge-danger">CONFIDENTIAL</span>
      </div>

      <div className="report-content">
        <ReactMarkdown>{report}</ReactMarkdown>
      </div>
    </div>
  )
}
